infrastructure:
  - changed-files:
      - any-glob-to-any-file: "*.tf"

security:
  - changed-files:
      - any-glob-to-any-file: "iam.tf"
      - any-glob-to-any-file: "security_groups.tf"

github-actions:
  - changed-files:
      - any-glob-to-any-file: ".github/workflows/**"

documentation:
  - changed-files:
      - any-glob-to-any-file: "*.md"