infrastructure:
  - "terraform/**/*"
  - "environments/**/*"

security:
  - "**/iam.tf"
  - "**/security_groups.tf"

production:
  - "environments/prod/**/*"

documentation:
  - "**/*.md"

github-actions:
  - ".github/workflows/**/*"
