name: PR Default Checks

on:
  pull_request:
    branches:
      - main

jobs:
  basic-checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: YAML lint
        uses: ibiqlik/action-yamllint@v3

      - name: Markdown lint
        uses: DavidAnson/markdownlint-cli2-action@v16
