name: Terraform Plan Comment

on:
  pull_request:

jobs:
  plan-comment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - run: terraform init

      - id: plan
        run: terraform plan -no-color > plan.txt
        continue-on-error: true

      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: plan.txt
