name: Terratest

on:
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terratest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::108703420068:role/github-oidc-role
          aws-region: us-east-1

      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - uses: hashicorp/setup-terraform@v3

      - run: go mod download

      - run: go test ./test -v -timeout 30m
